class GameConstants {
  static const List<String> alphabet = [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z'
  ];

  // Add other game-related constants here if needed
}

// Word Bomb specific constants - can be moved to a WordBomb specific constants file if preferred
const List<String> wordBombCategories = [
  "Città Italiane",
  "Animali",
  "Cose che si trovano in cucina",
  "Marche di Automobili",
  "Nomi Propri di Persona",
  "Sport",
  "Mestieri",
  "Frutta",
  "Verdura",
  "Nazioni del Mondo",
  "Strumenti Musicali",
  "Capi di Abbigliamento",
  "Parti del Corpo Umano",
  "Fiori",
  "Colori",
  "Bevande",
  "Dolci",
  "Attori Famosi",
  "Cantanti Famosi",
  "Film Famosi",
  "Libri Famosi",
  "Personaggi Storici",
  "Divinità Mitologiche",
  "Elementi Chimici",
  "Pianeti del Sistema Solare",
  "Videogiochi",
  "Cartoni Animati",
  "Supereroi",
  "Cose tonde",
  "Cose quadrate",
  "Cose che volano",
  "Cose che si mangiano a colazione",
  "Cose che si usano in bagno",
  "Parolacce (con moderazione!)",
  "Modi di dire",
  "Razze di Cani",
  "Capitali Europee",
  "Fiumi Italiani",
  "Montagne Famose",
  "Isole Famose",
  "Piatti Tipici Italiani",
  "Cocktail",
  "Marche di Telefoni",
  "Social Network",
  "Programmi TV",
  "Materie Scolastiche",
  "Attrezzi da Lavoro",
  "Hobby",
  "Cose che si comprano al supermercato",
  "Cose che iniziano con la 'S' (esempio di categoria tematica)",
  "Cose che si trovano in spiaggia",
  "Cose che si fanno in vacanza",
];
